ForgeRock/forgerock-ios-sdk

CHANGELOG.md
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Manager/KeychainManager.swift
FRAuth/FRAuth/User/FRUser.swift
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCoreTests/FRCore/Util/KeychainServiceTests.swift
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI/FRUI.xcodeproj/project.pbxproj
FRUI/FRUI/ViewControllers/AuthStepViewController.swift
FRUI/FRUI/ViewControllers/AuthStepViewController.xib
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
SampleApps/FRexampleObjC/FRexampleObjC.xcodeproj/project.pbxproj

- SDKS-552 : SSO mistakenly allowing other app's private storage access when mis-configured .entitlement
- Updating CHANLGELOG.md / module version number changes for next release
- FRUI auth screen alignment for page header and description

Sdks 552 sso keychain access group

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth/Callbacks/DeviceProfileCallback.swift
FRAuth/FRAuth/Callbacks/MultipleValuesCallback.swift
FRAuth/FRAuth/Callbacks/SingleValueCallback.swift
FRAuth/FRAuth/Device/BrowserCollector.swift
FRAuth/FRAuth/Device/HardwareCollector.swift
FRAuth/FRAuth/Device/NetworkCollector.swift
FRAuth/FRAuth/Device/PlatformCollector.swift
FRAuth/FRAuth/Device/TelephonyCollector.swift
FRAuthenticator.podspec
FRCore.podspec
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRProximity/FRProximity/Device/BluetoothCollector.swift
FRProximity/FRProximity/Device/LocationCollector.swift
FRProximity/FRProximity/FRProximity.swift
FRProximity/FRProximity/Location/FRLocationManager.swift
FRProximity/FRProximity/Log/FRPLog.swift
FRProximity/FRProximityTests/E2ETests/DeviceCollectorNodeTests.swift
FRProximity/FRProximityTests/UnitTests/DeviceProfileCallbackTests.swift
FRProximity/FRProximityTests/UnitTests/FRProximityTests.swift
FRProximity/FRProximityTests/UnitTests/LocationCollectorTests.swift
FRUI.podspec
SampleApps/FRExample/FRExample/ViewController.swift

Updating .podspec for release 2.1.0

Sdks 537 release 2 1 0

---

FRAuth/FRAuth/OAuth2/AccessToken.swift
FRAuth/FRAuth/OAuth2/Token.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/OAuth2/AccessTokenTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/OAuth2/TokenTests.swift

AccessToken class now implementing the Encodable protocol

SDKS-1046-Encodable protocol for access token

---

CHANGELOG.md
FRAuth.podspec
FRAuthenticator.podspec
FRCore.podspec
FRFacebookSignIn.podspec
FRGoogleSignIn.podspec
FRProximity.podspec
FRUI.podspec

* Updated CHANGELOG for the release.
* Updated version number to 3.1.0 in the podspec files.

ForgeRock iOS SDK 3.1.0 Release Preparation

---

CHANGELOG.md
FRAuth.podspec
FRAuthenticator.podspec
FRCore.podspec
FRFacebookSignIn.podspec
FRGoogleSignIn.podspec
FRProximity.podspec
FRUI.podspec

* Updated CHANGELOG.md
* Updated release version to 3.1.1 in the podspec files.

ForgeRock iOS SDK 3.1.1 Release Preparation

---

CHANGELOG.md
FRAuth.podspec
FRAuthenticator.podspec
FRCore.podspec
FRFacebookSignIn.podspec
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn/FRGoogleSignIn/Sources/GoogleSignInHandler.swift
FRProximity.podspec
FRUI.podspec
LICENSE
Package.swift
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

Update GoogleSign In dependency and add SPM support

SDKS-1256 update google sign in

---

FRUI/FRUI/Views/IdPValueTableViewCell.swift

(second attempt, first time the commit was not signed)

Fix Social Login buttons not displayed on iOS 15.x devices

---

FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj

Updated release version numbers in projects and podspecs.

ForgeRock iOS SDK 3.2.0 Release

---

CHANGELOG.md
FRAuth/FRAuth/Manager/TokenManager.swift

[SDKS-1824](https://bugster.forgerock.org/jira/browse/SDKS-1824)
Fix the bug when refreshing the access token we return the old token

Fix the bug when refreshing the access token we return the old token

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Device/AtomicDictionary.swift
FRAuth/FRAuth/Device/FRDeviceCollector.swift
FRAuth/FRAuth/Device/ProfileCollector.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Device/AtomicDictionaryTests.swift

SDKS 1912 concurrent

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj

n/a
ForgeRock iOS SDK 3.3.1 Release preparation

ForgeRock iOS SDK 3.3.1 Release preparation.

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/bitbar-results.yaml
.github/workflows/bitbar-run.yaml
.github/workflows/build-and-test.yaml
.github/workflows/ci.yaml
README.md

[SDKS-1770](https://bugster.forgerock.org/jira/browse/SDKS-1770) - [CI/CD][iOS] Execute e2e tests on BitBar via Github actions
- Split the CI pipeline into smaller chunks
- Added workflows for preparing and executing e2e tests in BitBar

Execute e2e tests in BitBar

---

CHANGELOG.md
FRAuth/FRAuth/Device/NetworkCollector.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Network/NetworkReachabilityMonitorTests.swift

[SDKS-1931](https://bugster.forgerock.org/jira/browse/SDKS-1931)
Change to capture reachabilityMonitor as weak in reachabilityMonitor.monitoringCallback to avoid memory leaks. 
Add Unit tests to prove this

Sdks 1931 fix memory leak

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_04_NumberAttributeInputCallbackTest.swift
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj

[SDKS-1942](https://bugster.forgerock.org/jira/browse/SDKS-1942) ForgeRock iOS SDK 3.3.2 Release
Preparation for the ForgeRock iOS 3.3.2 Release

ForgeRock iOS SDK 3.3.2 Release preparation.

---

FRAuth/FRAuth/Config/FROptions.swift

SDKS-1983 Adding scopes and redirect URI in the FROption comparison function

---

FRAuth/FRAuth/Config/FROptions.swift
FRAuth/FRAuth/FRAuth.swift

Fixed an issue where if on the FROptions no oauth endpoints are set, the property getters return null

SDKS-2080_Dynamic_config_endpoint_getters

---

FRAuth/FRAuth/Config/FROptions.swift
FRAuth/FRAuth/FRAuth.swift
FRAuth/FRAuth/Manager/KeychainManager.swift

Moved FROptions storage in UserDefaults and changed the logic so that in case of a new Config the old one is loaded first and the clean up is performed

SDKS-2092 Starting the SDK with new configuration with different client_id and cookie_name fails to revoke previous SSO and Access Tokens

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/build-and-test.yaml
FRCore/FRCore/Network/FRURLSessionHandler.swift
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
SampleApps/FRexampleObjC/FRexampleObjC/ViewController.m

Small changes in FRURLSessionHandler to fix new XCode build errors and fixes / updates for the FRExample OBJC project

SDKS-2073_XCode14_build_errors

---

FRAuth/FRAuth/Config/OAuth2Client.swift
FRTestHost/FRTestHost/SharedTestFiles/TestUtil/FRTestNetworkStubProtocol.swift

[SDKS-2077](https://bugster.forgerock.org/jira/browse/SDKS-2077)
Add verification for State value when calling the Authorize endpoint

Add verification for State value when calling the Authorize endpoint

---

FRCore/FRCore/Keychain/SecuredKey.swift
FRCore/FRCoreTests/FRCore/Util/SecuredKeyTests.swift

WIP updating the securedKey algorithm with newer suggested variant in a non-breaking way

SDKS-1994_New_SecuredKey_Algorithm - For SDK 4.0 Release

---

FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Cookie/CookieTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Cookie/CookieValidationTests.swift
FRTestHost/FRTestHost/FRAuthConfigPKHash.plist

(cherry picked from commit 8be38a100081f649758c42a6c4dd7924077654c2)
Fix failing tests on Develop (due to expired cookies and cert)

Fix failing tests

---

FRAuth/FRAuth/DeviceBinding/KeyAware.swift

[SDKS-2188](https://bugster.forgerock.org/jira/browse/SDKS-2188)
Skip kSecAttrTokenIDSecureEnclave flag during private key generation on simulator

Fix Key generation error on simulator on older iOS versions

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj

[SDKS-2202](https://bugster.forgerock.org/jira/browse/SDKS-2202) ForgeRock iOS SDK 3.4.1 Release
Release preparation for the iOS SDK 3.4.1 release.

ForgeRock iOS SDK 3.4.1 Release preparation

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/DeviceBinding/DeviceBindingAuthenticators.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/DeviceBindingCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/DeviceAuthenticatorTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/KeyAwareTests.swift

[SDKS-2189](https://bugster.forgerock.org/jira/browse/SDKS-2189)
Added tests for the following entities:
DeviceBindingCallback
KeyAware
AuthenticatorFactory
None
BiometricAndDeviceCredential
BiometricOnly
DeviceAuthenticator

Add Device Binding tests

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2265](https://bugster.forgerock.org/jira/browse/SDKS-2265) ForgeRock iOS SDK 4.0.0-beta1 release
This PR updates the version numbers in the `.podspec` files. 
Once we merge it to the `develop` branch we will publish the packages from there, and create a `4.0.0-beta1` tag.

ForgeRock iOS SDK 4.0.0-beta1 release preparation

---

CHANGELOG.md
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Callbacks/Binding.swift
FRAuth/FRAuth/Callbacks/DeviceBindingCallback.swift
FRAuth/FRAuth/Callbacks/DeviceSigningVerifierCallback.swift
FRAuth/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticator.swift
FRAuth/FRAuth/DeviceBinding/CryptoAware.swift
FRAuth/FRAuth/DeviceBinding/DeviceBindingAuthenticators.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/DeviceBindingCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/DeviceSigningVerifierCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticatorTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/DeviceAuthenticatorTests.swift
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Authenticator/AppPinAuthenticator.swift
FRCore/FRCore/Authenticator/CryptoKey.swift
FRCore/FRCoreTests/FRCore/Authenticator/AppPinAuthenticatorTests.swift
FRCore/FRCoreTests/FRCore/Authenticator/CryptoKeyTests.swift

[SDKS-2137](https://bugster.forgerock.org/jira/browse/SDKS-2137)
Add Application PIN authenticator type to Device Binding and Device Signing Verification
Major Changes:
**//FRAuth**
- Added new Binding protocol in a separate file (DeviceBindingCallback and  DeviceSigningVerifierCallback now conform to Binding)
- Added new CryptoAware protocol in a separate file
- AuthenticatorFactory has been deleted all together (was in DeviceBindingAuthenticators). Instead DeviceBindingAuthenticationType enum has a new method getAuthType() that will create and return the correct DeviceAuthenticator
- DeviceBindingAuthenticationType enum has been moved from DeviceBindingCallback file to DeviceBindingAuthenticators file
- Added Prompt struct containing title, subtitle, description in …

SDKS-2137 Add Application PIN authenticator type 

---

.whitesource

Only scan the develop branch and make the build failing if there is a license violation
https://bugster.forgerock.org/jira/browse/RELENG-1924

RELENG-1924 Only scan develop

---

FRAuth/FRAuth/Callbacks/WebAuthnRegistrationCallback.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnRegistrationTests.swift
SampleApps/QuickstartExample/Quickstart.xcodeproj/project.pbxproj
SampleApps/QuickstartExample/Quickstart.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/QuickstartExample/Quickstart/LoginViewController.swift

JIRA: SDKS-2297
Added optional device name input property in the WebAuthRegistration.register() method
Added Unit test

SDKS-2297_Webauthn_Set_Device_Name

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2307](https://bugster.forgerock.org/jira/browse/SDKS-2307) ForgeRock iOS SDK 4.0.0-beta2 release
This PR updates the version numbers in the `.podspec` files. 
Once we merge it to the `develop` branch we will publish the packages from there, and create a `4.0.0-beta2` tag.

ForgeRock iOS SDK 4.0.0-beta2 release preparation

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2376](https://bugster.forgerock.org/jira/browse/SDKS-2376) ForgeRock iOS SDK 4.0.0-beta3 release
This PR updates the version numbers in the .podspec files.
Once we merge it into the develop branch we will publish the packages from there, and create a 4.0.0-beta3 tag.

ForgeRock iOS SDK 4.0.0-beta3 release preparation

---

FRAuth/FRAuth/Callbacks/DeviceBindingCallback.swift
FRAuth/FRAuth/Callbacks/DeviceSigningVerifierCallback.swift
FRAuth/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticator.swift
FRAuth/FRAuth/DeviceBinding/DeviceBindingAuthenticators.swift
FRAuth/FRAuth/DeviceBinding/DeviceBindingStatus.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/DeviceSigningVerifierCallbackTests.swift

[SDKS-2353](https://bugster.forgerock.org/jira/browse/SDKS-2353) [iOS] Device Binding/Singing Error not align with Android
Wiki page for error handling: https://wikis.forgerock.org/confluence/pages/viewpage.action?pageId=129970205#DeviceBinding&DeviceSigningVerifier(SDK)-ErrorHandling

Align Device Binding errors with the latest documentation

---

FRAuthenticator/FRAuthenticator/Manager/AuthenticatorManager.swift
FRAuthenticator/FRAuthenticator/Model/Account/Account.swift
FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathQRCodeParser.swift
FRAuthenticator/FRAuthenticator/Model/Mechanism/Push/PushQRCodeParser.swift
FRAuthenticator/FRAuthenticator/Policy/FRAPolicyEvaluator.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/AccountTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/OathQRCodeParserTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/PushQRCodeParserTests.swift
SampleApps/FRAuthenticatorExample/FRAuthenticatorExample/Cell/AccountTableViewCell.swift
SampleApps/FRAuthenticatorExample/FRAuthenticatorExample/Cell/AccountTableViewCell.xib

[SDKS-2382](https://bugster.forgerock.org/jira/browse/SDKS-2382) [FRA][iOS] New Authenticator Policies APIs are not public
The new FRAPolicyEvaluator class is not public, preventing developers to add their custom policies. While fixing this issue, another one was found, where the policies attribute was not populated in the Account object.

SDKS-2382 New Authenticator Policies APIs are not public

---

FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2383](https://bugster.forgerock.org/jira/browse/SDKS-2383) ForgeRock iOS SDK 4.0.0-beta4 release
- Updated the SDK version in podspec files and various other places.

ForgeRock iOS SDK 4.0.0-beta4 release preparation

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2406](https://bugster.forgerock.org/jira/browse/SDKS-2406) ForgeRock iOS SDK 4.0.0-beta5 release
Updated the SDK version in podspec files and various other places.

ForgeRock iOS SDK 4.0.0-beta5 release preparation

---

FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-06-DeviceSigningVerifierCallbackTest.swift
FRCore/FRCore/Authenticator/CryptoKey.swift
FRDeviceBinding/FRDeviceBinding/Sources/ApplicationPinDeviceAuthenticator.swift
FRDeviceBinding/FRDeviceBinding/Sources/DeviceBindingAuthenticators.swift
FRDeviceBinding/FRDeviceBindingTests/ApplicationPinDeviceAuthenticatorTests.swift
FRDeviceBinding/FRDeviceBindingTests/DeviceAuthenticatorTests.swift

[SDKS-2424](https://bugster.forgerock.org/jira/browse/SDKS-2424)
**[iOS] Add Issuer claim and platform claim to signed JWT for device binding.**
Add "iss" and "platform" claims to the binding JWS payload
Add "iss" to device singing verifier JWS payload
Define DBConstants and move all string literals there related to device binding
Update Unit Tests
Update/Add E2E tests

Sdks 2424 add issuer and platform

---

CHANGELOG.md
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn/FRGoogleSignIn/Sources/GoogleSignInHandler.swift
Package.swift
SampleApps/FRExample/FRExample/AppDelegate.swift

[SDKS-2426](https://bugster.forgerock.org/jira/browse/SDKS-2426)
Update Google SDK to the latest 7.0.0 version
Update Google SDK version in Package.swift and podspec
Update GoogleSignInHandler with the latest Google SDK API
Remove unused code that supports  iOS 10

Sdks 2426 update google sdk

---

FRAuth/FRAuth/Callbacks/WebAuthnAuthenticationCallback.swift
FRAuth/FRAuth/Callbacks/WebAuthnRegistrationCallback.swift
FRAuth/FRAuth/Constants/CallbackConstants.swift
FRAuth/FRAuth/Manager/KeychainManager.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/CallbackConstantsTests.swift

SDKS-2465_Removing default bundle ids and throwing errors or error outcomes

SDKS-2465_Removing default bundle ids and throwing errors or error outcomes

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/build-and-test.yaml
.github/workflows/ci.yaml
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/DeviceProfileCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Device/FRDeviceCollectorTests.swift
FRTestHost/FRTestHost.xcodeproj/xcshareddata/xcschemes/FRTestHostBitBar.xcscheme
FRTestHost/FRTestHost/Info.plist
FRTestHost/FRTestHostTests/Info.plist

Bumped Xcode version for CI to 14.3

Bump Xcode version

---

FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathQRCodeParser.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/HOTPMechanismTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/OathMechanismTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/PushMechanismTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/TOTPMechanismTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/OathQRCodeParserTests.swift
FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/PushQRCodeParserTests.swift
FRTestHost/FRTestHost/Info.plist

[SDKS-2542](https://bugster.forgerock.org/jira/browse/SDKS-2542) Combined MFA Registration not working properly
Issue on parsing Issuer parameter from mfauth scheme

SDKS-2542 Issue on parsing Issuer parameter from mfauth scheme

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRDeviceBinding.podspec
FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2573](https://bugster.forgerock.org/jira/browse/SDKS-2573) ForgeRock iOS SDK 4.1.0-beta2 Release
ForgeRock iOS SDK 4.1.0-beta2 release preparation

ForgeRock iOS SDK 4.1.0-beta2 release preparation

---

SampleApps/FRAuthenticatorExample/FRAuthenticatorExample/Controller/MainListViewController.swift
SampleApps/FRAuthenticatorExample/FRAuthenticatorExample/Controller/NotificationRequestViewController.swift

Move PushRequestInterceptor test code to MainListViewController in FRAuthenticatorExample

Move PushRequestInterceptor test code to MainListViewController in FRAuthenticatorExample

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRDeviceBinding.podspec
FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2659](https://bugster.forgerock.org/jira/browse/SDKS-2659) ForgeRock iOS SDK 4.1.1-beta1 Release

ForgeRock iOS SDK 4.1.1-beta1 release preparation

---

FRDeviceBinding/FRDeviceBinding/Sources/ApplicationPinDeviceAuthenticator.swift
FRDeviceBinding/FRDeviceBinding/Sources/DeviceBindingAuthenticators.swift
FRDeviceBinding/FRDeviceBindingTests/ApplicationPinDeviceAuthenticatorTests.swift
FRDeviceBinding/FRDeviceBindingTests/DeviceAuthenticatorTests.swift

[SDKS-2748](https://bugster.forgerock.org/jira/browse/SDKS-2748)
[iOS] Add iat and nbf claims for Device Binding and Design Signing signed JWT

Add iat and nbf to Device Binding jws payload

---

FRAuth/FRAuth/User/Browser.swift

[SDKS-2707](https://bugster.forgerock.org/jira/browse/SDKS-2707)
RFE - iOS SDK - Enable ephemeral session for authSession browserType
As _prefersEphemeralWebBrowserSession_ is only available in iOS13 and above, I added a new **ephemeralAuthSession** browser type marked available iOS 13 +

Add a new ephemeralAuthSession browser type

---

FRCore/FRCore/Network/RestClient.swift
FRCore/FRCoreTests/FRCore/Network/RestClientTests.swift
FRTestHost/FRTestHost.xcodeproj/xcshareddata/xcschemes/FRTestHost.xcscheme

[SDKS-2700](https://bugster.forgerock.org/jira/browse/SDKS-2700)
[iOS] Inadequate Cache Control - Mobile Application
Approach 2

Set default Session Configuration's urlCache to nil

---

FRAuth/FRAuth/Callbacks/FRAppIntegrityCallback.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_07_AppIntegrityTest.swift
FRTestHost/FRTestHost/SharedTestFiles/BaseTest/FRBaseTestCase.swift
FRUI/FRUI/ViewControllers/AuthStepViewController.swift

[SDKS-2785](https://bugster.forgerock.org/jira/browse/SDKS-2785) App Integrity QA
Implemented e2e test cases covering the App Integrity feature. The test cases require "live" AM server with the following tree:

App Integrity e2e test cases

---

FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/DeviceBindingCallback.swift
FRDeviceBinding/FRDeviceBindingTests/DeviceBindingCallbackTests.swift

[SDKS-2887](https://bugster.forgerock.org/jira/browse/SDKS-2887)
[iOS] Make sure iOS removes the device binding key record from local device repo on failure

Fix the bug when device binding local key was not deleted

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRDeviceBinding.podspec
FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-2851](https://bugster.forgerock.org/jira/browse/SDKS-2851)
ForgeRock iOS SDK 4.3.0 release preparation

ForgeRock iOS SDK 4.3.0 release preparation

---

FRAuth/FRAuth/AppIntegrity/FRAppAttestDomainModal.swift
FRAuth/FRAuth/Callbacks/FRAppIntegrityCallback.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_07_AppIntegrityTest.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/AppIntegrity/FRAppAttestDomainModalTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/FRAppIntegrityCallbackTests.swift

AppIntegrity to expose optional payload to sign for client

---

.github/workflows/ci.yaml
.github/workflows/mend-cli-scan.yaml

[SDKS-3025](https://bugster.forgerock.org/jira/browse/SDKS-3025) [iOS][CICD] Automate WhiteSource (Mend) Scan
- Added Mend CLI scan
- The scan automatically updates the `Mobile//forgerock-ios-sdk` project in Mend
- The pipeline will fail if a Critical or High vulnerability is discovered 
Currently our project only depends on these libraries and these are the ones that Mend scans:

SDKS-3025 Automate Mend Scan

---

FRCore/FRCore/Network/Request.swift
FRCore/FRCoreTests/FRCore/Network/RequestTests.swift
FRCore/FRCoreTests/FRCore/Network/RestClientTests.swift
FRCore/FRCoreTests/FRCore/RequestInterceptor/RequestInterceptorTests.swift

[SDKS-2997](https://bugster.forgerock.org/jira/browse/SDKS-2997)
[iOS] Send header attribute identifying the SDK

Add platform identifying headers to request

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRDeviceBinding.podspec
FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
PingProtect.podspec
PingProtect/PingProtect.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-3017](https://bugster.forgerock.org/jira/browse/SDKS-3017) ForgeRock iOS SDK 4.4.0 release preparation
- Updated CHANGELOG.md
- Updated version number in all podspec files and project files
- Updated version number in FRCore/FRCore/Log/Log.swift

ForgeRock iOS SDK 4.4.0 release preparation

---

PingProtect.podspec

[SDKS-3017](https://bugster.forgerock.org/jira/browse/SDKS-3017) Release activities for SDK 4.4.0 
- Fixed PingOneSignals path

SDKS-3017 Fixed PingOneSignals path

---

FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRAuthenticator/FRAuthenticator/PrivacyInfo.xcprivacy

[SDKS-3086](https://bugster.forgerock.org/jira/browse/SDKS-3086) [iOS] Add Privacy Manifests to SDK

Add Privacy Manifest to FRAuthenticator

---

CHANGELOG.md
FRAuth.podspec
FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuthenticator.podspec
FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
FRCore.podspec
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Log/Log.swift
FRDeviceBinding.podspec
FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
FRFacebookSignIn.podspec
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn.podspec
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRProximity.podspec
FRProximity/FRProximity.xcodeproj/project.pbxproj
FRUI.podspec
FRUI/FRUI.xcodeproj/project.pbxproj
PingProtect.podspec
PingProtect/PingProtect.xcodeproj/project.pbxproj
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

[SDKS-3094](https://bugster.forgerock.org/jira/browse/SDKS-3094) ForgeRock iOS SDK 4.4.1 release preparation
- Updated CHANGELOG.md
- Updated version number in all podspec files and project files
- Updated version number in FRCore/FRCore/Log/Log.swift

ForgeRock iOS SDK 4.4.1 release preparation

---

FRAuthenticator/FRAuthenticator/PrivacyInfo.xcprivacy
FRCore/FRCore/PrivacyInfo.xcprivacy
FRDeviceBinding/FRDeviceBinding/PrivacyInfo.xcprivacy
FRGoogleSignIn/FRGoogleSignIn/PrivacyInfo.xcprivacy
FRProximity/FRProximity/PrivacyInfo.xcprivacy
FRUI/FRUI/PrivacyInfo.xcprivacy
PingProtect/PingProtect/PrivacyInfo.xcprivacy

Update Privacy Manifests

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorMakeCredentialSession.swift
FRAuth/FRAuth/WebAuthn/Client/Operation/ClientCreateOperation.swift
FRAuth/FRAuth/WebAuthn/FRWebAuthn.swift
FRAuth/FRAuth/WebAuthn/RemoteWebAuthnRepository.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/FRWebAuthnTests.swift

[SDKS-1753](https://bugster.forgerock.org/jira/browse/SDKS-1753) WebAuthn Device Management

SDKS-1753 WebAuthn Device Management

---

FRAuth/FRAuth/Network/FRURLProtocol.swift
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/FRExample/FRExample/ViewController.swift

Please, link jira ticket here.](https://bugster.forgerock.org/jira/browse/SDKS-3239)
Fix for SSL Pinning and FRURLProtocol uses

FRURLProtocol ignores ssl pinning

---

FRAuth/FRAuth/OAuth2/AccessToken.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/OAuth2/AccessTokenTests.swift

Change Access Token not to require scope. 
Update Unit Tests

Remove scope validation in Access Token

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Authentication/Node.swift
FRAuth/FRAuth/Callbacks/TextOutputCallback.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_11_TextOutputCallbackTest.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/TextOutputCallbackTests.swift

[SDKS-3226](https://bugster.forgerock.org/jira/browse/SDKS-3226)
Version 2

Fix to ignore ScriptedTextOutputCallbacks from the response.

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Authentication/Node.swift
FRAuth/FRAuth/Authentication/NodeAware.swift
FRAuth/FRAuth/Callbacks/DerivableCallback.swift
FRAuth/FRAuth/Callbacks/MetadataCallback.swift
FRAuth/FRAuth/Callbacks/ProtectCallback.swift
FRAuth/FRAuth/Constants/CallbackConstants.swift
PingProtect/PingProtect/Sources/Callbacks/PingOneProtectEvaluationCallback.swift
PingProtect/PingProtect/Sources/Callbacks/PingOneProtectInitializeCallback.swift
PingProtect/PingProtect/Sources/Constants/CallbackConstants.swift
PingProtect/PingProtectTests/PingOneProtectEvaluationCallbackTests.swift
PingProtect/PingProtectTests/PingOneProtectInitializeCallbackTests.swift

[SDKS-3296](https://bugster.forgerock.org/jira/browse/SDKS-3296) Support Marketplace PingOne Protect nodes
Make sure that the iOS SDK supports the PingOne Protect nodes offered in the Marketplace, which utilized the MetadataCallback.

SDKS-3296 Support Marketplace PingOne Protect nodes

---

FRAuth/FRAuth/Authorization/PolicyAdvice.swift
FRAuth/FRAuth/Authorization/PolicyAdviceCreator.swift

Making the PolicyAdviceCreator Public. Creating public init and exposing required methods
SDKS-3349

SDKS-3349_Make_PolicyAdviceCreator_public

---

FRAuth/FRAuth/User/FRUser.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FRURLProtocol/FRURLProtocolTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/SSL Pinning/SSLPinningTests.swift
FRCore/FRCore/Network/FRSecurityConfiguration.swift
FRCore/FRCoreTests/FRCore/Network/RestClientTests.swift
FRTestHost/FRTestHost/FRAuthConfigPKHash.plist
FRTestHost/FRTestHost/SharedTestFiles/BaseTest/FRBaseTestCase.swift

Improving SSL Pinning to support 4096 root certificates and conditional use of newer cert chain methods due to iOS 15 deprecations
SDKS-3334

SDKS-3334_SSL_Pinning_Root

---

FRAuth/FRAuth/User/FRUser.swift

[Please, link jira ticket here.](https://bugster.forgerock.org/jira/browse/SDKS-3348)
Importing UIKit on the FRUser class

SDKS-3348_UIViewController_scope_missing

---

FRGoogleSignIn.podspec

Removing EXCLUDED_ARCHS from PodSpec of FRGoogleSignIn module
This needs to be tested in both Intel and M1 Macs

SDKS-3347_arm64_architecture_pods

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/build-and-test.yaml
.github/workflows/mend-cli-scan.yaml
FRAuth/FRAuth/FRAuth.swift
FRCaptchaEnterprise.podspec
FRCaptchaEnterprise/FRCaptchaEnterprise.xcodeproj/project.pbxproj
FRCaptchaEnterprise/FRCaptchaEnterprise.xcodeproj/xcshareddata/xcschemes/FRCaptchaEnterprise.xcscheme
FRCaptchaEnterprise/FRCaptchaEnterprise/FRCaptchaEnterprise.h
FRCaptchaEnterprise/FRCaptchaEnterprise/PrivacyInfo.xcprivacy
FRCaptchaEnterprise/FRCaptchaEnterprise/Sources/Callbacks/ReCaptchaEnterpriseCallback.swift
FRCaptchaEnterprise/FRCaptchaEnterprise/Sources/CaptchaConstant.swift
FRCaptchaEnterprise/FRCaptchaEnterprise/Sources/FRCaptchaEnterprise.swift
FRCaptchaEnterprise/FRCaptchaEnterpriseTests/FRCaptchaEnterpriseTests.swift
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRTestHost/FRTestHost.xcodeproj/xcshareddata/xcschemes/FRTestHost.xcscheme
FRUI/FRUI/ViewControllers/AuthStepViewController.swift
Package.swift
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj

SDKS-3324 Support new ReCaptcha Enterprise node

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/build-and-test.yaml
.github/workflows/mend-cli-scan.yaml
SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved

- Updated XCode version to 15.4

SDKS-3324 update xcode version

---

FRUI/FRUI.xcodeproj/project.pbxproj

SDKS-Fix Build

---

FRAuth/FRAuth/Authentication/AuthService.swift
FRAuth/FRAuth/Authentication/Node.swift
FRAuth/FRAuth/Constants/OpenAM.swift
FRAuth/FRAuth/Manager/KeychainManager.swift
FRAuth/FRAuth/OAuth2/Token.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/OAuth2/TokenTests.swift

[SDKS-3352](https://bugster.forgerock.org/jira/browse/SDKS-3352)
[iOS] - Expose realm, Success  URL in GetSessionToken

Expose success url and realm in getSessionToken

---

FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/SocialLogin/AppleSignInHandlerTests.swift
FRCaptchaEnterprise/FRCaptchaEnterprise.xcodeproj/project.pbxproj
FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
FRFacebookSignIn/FRFacebookSignInTests/FacebookSignInHandlerTests.swift
FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
FRGoogleSignIn/FRGoogleSignInTests/GoogleSignInHandlerTests.swift
FRTestHost/FRTestHost.xcodeproj/project.pbxproj
FRUI/FRUI.xcodeproj/project.pbxproj
PingProtect/PingProtect.xcodeproj/project.pbxproj

[SDKS-3429](https://bugster.forgerock.org/jira/browse/SDKS-3429)
Fix Tests Issues and add improvements
1. Add FRCaptchaEnterprise to FRUI and to FRTestHost
2. Add FRTestHost as and host app to FRCaptchaEnterprise, FRFacebookSignIn, FRGoogleSignIn, FRUI, PingProtect
3. Change idp tests due to FB and google handlers availability

Sdks 3429 fix tests

---

FRAuth/FRAuth.xcodeproj/project.pbxproj
FRAuth/FRAuth/Constants/OpenAM.swift
FRAuth/FRAuth/SelfService/Device.swift
FRAuth/FRAuth/SelfService/DeviceClient.swift
FRAuth/FRAuth/SelfService/Session.swift
FRAuth/FRAuth/Util/CodableExtentions.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/SelfService/DeviceClientTests.swift
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/accessDenied.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/forbidden.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/sessionInfo.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successDeviceBinding.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successDeviceProfile.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successOath.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successPush.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successUpdateDeviceBinding.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successUpdateDeviceProfile.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successUpdateWebAuthn.json
FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/SelfService/successWebAuthn.json
SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
SampleApps/FRExample/FRExample/ViewController.swift
SampleApps/FRExample/FRExample/ViewControllers/ClientDevicesTableViewController.swift

[SDKS-3409](https://pingidentity.atlassian.net/browse/SDKS-3409) [iOS] Implement Developer-facing API Interface for Self-Management 
Please review the feature implementation and the unit tests
FRExample changes are still pending

Self device management implementation

---

FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/SelfService/DeviceClientTests.swift

[SDKS-3412](https://pingidentity.atlassian.net/browse/SDKS-3412) QA Testing for Developer-facing API Interface for Self-Management
- Updated the device client tests to use the correct interfaces for retrieving user's devices.

SDKS-3412 Test the Self-Management APIs

---

FRAuth/FRAuth/SelfService/Device.swift
FRCore/FRCore.xcodeproj/project.pbxproj
FRCore/FRCore/Security/DyldDetector.swift
FRCore/FRCore/Security/FRJailbreakDetector.swift
FRCore/FRCore/Security/SandboxRestrictedFilesAccessable.swift

[SDKS-3693](https://pingidentity.atlassian.net/browse/SDKS-3693)
[iOS][SPIKE] Detect jailbroken devices using palera1n

Sdks 3693 jailbreak detectors

---

CHANGELOG.md
README.md

[SDKS-3707](https://pingidentity.atlassian.net/browse/SDKS-3707)
Updating links that went to BackStage.
N/A

SDKS-3707 Update documentation links in README files.

---

FRAuth/FRAuth/SelfService/DeviceClient.swift

[SDKS-3703](https://pingidentity.atlassian.net/browse/SDKS-3703)  [iOS] DeviceClient Not Using the FRCore Rest Client
Added a async/await version of FRRestClient.invoke in an extension and used that in DeviceClient

Sdks 3703 device client improvements

---

FRAuth/FRAuth/Device/NetworkCollector.swift

Adding an extra completion and changing the order of assigning the callback to the reachability monitor to avoid racing conditions
Please, link jira ticket here. [SDKS-3827]

SDKS-3827_Reachability_improvements

---

FRAuth/FRAuth/Callbacks/WebAuthnAuthenticationCallback.swift
FRAuth/FRAuth/Callbacks/WebAuthnCallback.swift
FRAuth/FRAuth/Callbacks/WebAuthnRegistrationCallback.swift
FRAuth/FRAuth/Constants/CallbackConstants.swift
FRAuth/FRAuth/WebAuthn/FRWebAuthnManager.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/WebAuthnAuthenticationCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/WebAuthnRegistrationCallbackTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/FRWebAuthnTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnAuthenticationTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnRegistrationTests.swift
FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnSharedUtils.swift

Please, link jira ticket here. [SDKS-3842]
Webauthn new response payload

SDKS-3842 web authn improvements

---

.github/pull_request_template.md
CONTRIBUTION.md
README.md

SDKS-3969
Clearly define external guidelines for PRs against SDKs

SDKS-3969 Clearly define external guidelines for PRs against SDKs

---

FRAuth/FRAuth/Device/FRDeviceCollector.swift
FRAuth/FRAuth/Device/FRDeviceIdentifier.swift
FRAuth/FRAuth/Manager/KeychainManager.swift
FRCore/FRCore/Keychain/KeychainService.swift

Migrating old deviceIdentifier before creating the new keychain store if an old value exists
Please link jira ticket here, if applicable.

Fixing Device Identifier on 4.8.1 issues and providing migration

---

FRAuth/FRAuth/User/Browser.swift

Removing extra completion call on browser when the ASWebAuthentication is used.
Please link jira ticket here, if applicable.
[https://pingidentity.atlassian.net/browse/SDKS-4345](SDKS-4345)

SDKS-4345 Fixes for extra closure call on Browser.swift
