ForgeRock/forgerock-ios-sdk

- CHANGELOG.md
- FRAuth/FRAuth/Callbacks/DeviceProfileCallback.swift
- FRAuth/FRAuth/Callbacks/MultipleValuesCallback.swift
- FRAuth/FRAuth/Callbacks/SingleValueCallback.swift
- FRAuth/FRAuth/Device/BrowserCollector.swift
- FRAuth/FRAuth/Device/HardwareCollector.swift
- FRAuth/FRAuth/Device/NetworkCollector.swift
- FRAuth/FRAuth/Device/PlatformCollector.swift
- FRAuth/FRAuth/Device/TelephonyCollector.swift
- FRProximity/FRProximity.xcodeproj/project.pbxproj
- FRProximity/FRProximity/Device/BluetoothCollector.swift
- FRProximity/FRProximity/Device/LocationCollector.swift
- FRProximity/FRProximity/FRProximity.swift
- FRProximity/FRProximity/Location/FRLocationManager.swift
- FRProximity/FRProximity/Log/FRPLog.swift
- FRProximity/FRProximityTests/E2ETests/DeviceCollectorNodeTests.swift
- FRProximity/FRProximityTests/UnitTests/DeviceProfileCallbackTests.swift
- FRProximity/FRProximityTests/UnitTests/FRProximityTests.swift
- FRProximity/FRProximityTests/UnitTests/LocationCollectorTests.swift
- SampleApps/FRExample/FRExample/ViewController.swift
Following items were changed to align location collection behavior of iOS SDK to Android and JavaScript SDK:
- Change LocationCollector class to request for authorization when the authorization is not asked yet
- Create FRLocationManager class to manage and collect location and/or authorization 
- FRLocationManager checks Privacy Consent in .plist file of the application to determine if SDK can request for authorization
- If the location permission is denied, or restricted, still proceed with LocationCollector with null
- Exposing some of DeviceCollector classes that were private
- Update all FRProximity test cases to reflect changes
- Allow developers to change location accuracy configuration used by CLLocationManager within FRProximity SDK
> Sdks 617 fr proximity location

- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathQRCodeParser.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/OathQRCodeParserTests.swift
This fix address an issue on persist the `image` attribute from a QRCode for OATH registration. The SDK was expecting the attribute to be Base64 encoded. It's only the case for Push accounts, OATH accounts usually has the image value as URL encoded or plain text. Support for image value as Base64 was kept as well.
Unit tests were added to test the changes.
> SDKS-993 Image attribute in QRCode not persisted by SDK

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/FRAClient.swift
- FRAuthenticator/FRAuthenticator/Manager/AuthenticatorManager.swift
- FRAuthenticator/FRAuthenticator/Storage/KeychainServiceClient.swift
- FRAuthenticator/FRAuthenticator/Storage/StorageClient.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/FRAClient/FRAClientTests.swift
- FRAuthenticator/FRAuthenticatorTests/TestUtils/DummyStorageClient.swift
On this change a new getAllNotifications() method is exposed on the FRAClient class. This will allow developers to retrieve a single list of notifications across all mechanisms.
> SDKS-1009 Expose API to get all push notifications stored

- CHANGELOG.md
- FRAuth/FRAuth/Callbacks/SingleValueCallback.swift
- FRAuth/FRAuth/Config/ServerConfig.swift
- FRAuth/FRAuth/Constants/Typealias.swift
- FRAuth/FRAuth/FRAuth.swift
- FRAuth/FRAuth/Network/FRURLProtocol.swift
- FRAuth/FRAuth/Policy/TokenManagementPolicy.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Policy/TokenManagementPolicyTests.swift
- FRProximity/FRProximityTests/E2ETests/DeviceCollectorNodeTests.swift
- Removed ServerConfig deprecated public initializer
- Deleting deprecated FRAuth.shared.next() (public func next<T>) method from FRAuth.swift
- Removed FRURLProtocol.validatedURLs from FRURLProtocol.swift
- Removed deprecated FRURLProtocolResponseEvaluationCallback and dependencies from Typealias.swift, FRURLProtocol.swift, TokenManagementPolicy.swift
- Removed public var value from SingleValueCallback. The var has been replaced by getValue and setValue methods
> SDKS-910-Remove_deprecated_methods

- FRAuth/FRAuth/User/Browser.swift
iOS 14.5 has introduced a change not allowing the callBackURLScheme to contain the full URI but requires only the scheme (ex: frauth not frauth://).
Passing the redirectUri.scheme instead of full URL solved the issue
> SDKS-1157-FRExample - SDK crashes when attempting Centralised Login

- FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
- FRAuthenticator/FRAuthenticator/Constants/FRAConstants.swift
- FRAuthenticator/FRAuthenticator/FRAClient.swift
- FRAuthenticator/FRAuthenticator/Manager/AuthenticatorManager.swift
- FRAuthenticator/FRAuthenticator/Model/Account/Account.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/Mechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/HOTPMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/TOTPMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/Push/PushMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticator/Storage/KeychainServiceClient.swift
- FRAuthenticator/FRAuthenticator/Storage/StorageClient.swift
- FRAuthenticator/FRAuthenticator/Util/FRDateUtil.swift
- FRAuthenticator/FRAuthenticator/Util/FRJSONEncoder.swift
- FRAuthenticator/FRAuthenticatorTests/TestUtils/DummyStorageClient.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/AccountTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/HOTPMechanismTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/MechanismTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/NotificationTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/OathMechanismTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/PushMechanismTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/TOTPMechanismTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Storage/KeychainServiceStorageClientTests.swift
**Summary of changes:**
- Make `mechanismUUID` public on `PushNotification` and `Mechanism` objects
- Make notificationId use `timeAdded` in milliseconds
- Added new `getNotification()` API
- Refactored `toJson()` method on Models. It was not supposed to expose sensitive information. Also, it will align the output with Android SDK. So, some attributes may have different names in the json string.
> SDKS 1186 Authenticator SDK notification enhancements

- FRAuth/FRAuth/Authentication/Node.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_04_PageCallback_SDKS_1209.swift
Checking if the stage property has been set before going through the MetadataCallback to set the stage of the node.
> SDKS-1209-Metadata callback overrides stage property of node

- CHANGELOG.md
- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Network/FRHTTPCookie.swift
- FRAuth/FRAuth/Network/FRRestClient.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Cookie/CookieTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Cookie/CookieValidationTests.swift
- FRAuthenticator/FRAuthenticator/Storage/KeychainServiceClient.swift
- FRCore/FRCore/Keychain/SecuredKey.swift
OS make sure that deprecated "unarchiveObject(with:" methods are not used for iOS 11+
Based on the report from: https://forgerock.zendesk.com/agent/tickets/67734
- Added FRHTTPCookie class to support NSSecureCoding
- Fixed FRRestClient to only unarchive using NSSecureCoding methods for iOS 11+
- Fixed KeychainServiceClient to only unarchive using NSSecureCoding methods for iOS 11+
> Sdks-1366_iOS make sure that deprecated "unarchiveObject(with:" methods are not used for iOS 11+

- FRAuth/FRAuth/Log/FRLog.swift
- FRAuthenticator/FRAuthenticator/Log/FRALog.swift
- FRCore/FRCore/Log/Log.swift
- FRProximity/FRProximity/Log/FRPLog.swift
So the problem we had was that we were reading the SDK bundle version from CFBundleShortVersionString in Info.plist. This was working great with cocoapods as cocoapods creates a project for each module under the main workspace. In case of SPM, we have only one project and it gets the main app's version (which is not what we want).
I have tried a few things, like adding a variable to Package.swift and using it as a value in target's build settings (I followed the way google did in the signin package) and then trying to read it in Info.plist. But that didn't work at all.
I have also just tried to hardcode it in the Info.plist in each module, but then realized that we don't include the Info.plist files in the SPM package (we even explicitly exclude them). This also could have been the reason …
> Add sdkVersion constant to FRCore.Log class and use it instead of CFBundleShortVersionString

- FRAuth/FRAuth/Config/OAuth2Client.swift
Fix in OAuth2Client class to pass the cookie(sso token) as a header field, not a query param
> Sdks-1708_inject cookie to header instead of query param

- CHANGELOG.md
- FRAuth/FRAuth/Config/OAuth2Client.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FRAuth/FRAuthTests.swift
- FRCore/FRCore/Log/Log.swift
- FRCore/FRCore/Network/Request.swift
Remove _accept: application/x-www-form-urlencoded_ header from /authorize endpoint for GET requests
I checked Android SDK. They don't send any response header.
> Remove response header from /authorize GET call

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathQRCodeParser.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/OathQRCodeParserTests.swift
Add error checking for invalid and negative refresh periods in OathQRCodeParser. 
Add tests
>  Issues with registering TOTP accounts with invalid period

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Push/PushNotificationAuthenticationTests.swift
Fix the bug when expired notification would show up as approved
Move saving notification to the storage to the request success block (similar to Android) - this also fixed the failing tests after the first commit
> Sdks 1491 expired push notification displayed as approved

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/NotificationTests.swift
Set _timeAdded_ from the new payload if available. Update and add unit tests
Please note that in iOS PushNotification doesn't have _timeExpired_ property. It has _isExpired_ property that is calculated based on _timeAdded_ and _ttl_
> SDKS-1665 - Obtain timestamp from new Push Notification payload

- SampleApps/FRExample/FRExample/Configs/FRAuthConfig.plist
Remove the example item from forgerock_ssl_pinning_public_key_hashes  array in the sample app's plist
> SDKS-1826 Remove the example item from forgerock_ssl_pinning_public_key_hashes 

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Model/NotificationTests.swift
Unit Tests implemented too. Please rereview 
[Add new properties to PushNotification, handle init, encoding/decoding](https://github.com/ForgeRock/forgerock-ios-sdk/commit/d53bb594aa4cad626603877b96486e1ebacc3d71)
[Add numbersChallengeArray that returns int array](https://github.com/ForgeRock/forgerock-ios-sdk/commit/412bc7121a857f2275593669fe740cf1fba36e84)
[Add new accept with challengeResponse method. Modify push handling notification to consider challenge type](https://github.com/ForgeRock/forgerock-ios-sdk/commit/aabc4dd1fc1b8bb006f58d4f57891f15d51aa82c) 
[Update changelog. Remove the check for pushtype if push is denied](https://github.com/ForgeRock/forgerock-ios-sdk/pull/131/commits/6c8548943614dea6c947a9655e60d5618cec39f3)
[Make decoding of newaly added properties optional for …
> Sdks 1775 add new payload attributes in the push notification

- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/OathQRCodeParser.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/AuthenticatorManager/AuthenticatorManagerTests.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/FRAClient/FRAClientTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/OathQRCodeParserTests.swift
[SDKS-1408](https://bugster.forgerock.org/jira/browse/SDKS-1408) Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)
While registering a new mechanism,  if "issuer" is provided as query parameter of the URI and isn't empty, it should replace the issuer in the path.
> SDKS-1408 Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)

- .github/workflows/run-live-tests.yaml
- FRTestHost/FRTestHost.xcodeproj/xcshareddata/xcschemes/FRTestHostE2E.xcscheme
- FRTestHost/FRTestHost/SharedTestFiles/TestConfig/Config-live-01.json
[SDKS-1789](https://bugster.forgerock.org/jira/browse/SDKS-1789) "Automate Cloud Upgrade Testing"
This PR adds workflow for triggering the e2e test cases against live IDCloud environment. The workflow is called "Run Live Tests". A new `FRTestHostE2E.xcscheme` scheme has been added to the project to filter the "live" test cases only.
The e2e tests now can be triggered either manually from the "Actions" menu in the repo, or via an HTTP request. 
Triggering the workflow via HTTP request requires a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (PAT) passed as a Bearer token in the Authorization header. For more details read the [workflow-dispatch-event](https://docs.github.com/en/rest/actions/workflows#c …
> Added workflow for triggering the e2e tests against IDCloud instance.

- README.md
SDK documentation now exists under `/latest`, and BackStage is our preferred URL base.
> Update links for new docs layout.

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
[SDKS-1750](https://bugster.forgerock.org/jira/browse/SDKS-1750) "Device Binding QA"
- e2e test cases for the Device Binding feature.
- These test cases assume that the target IDCloud instance supports the DeviceBinding node and contains the following authentication tree:
> SDKS-1750 Device Binding e2e test cases

- FRAuthenticator/FRAuthenticator/JWT/FRCompactJWT.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/JWT/FRCompactJWTTests.swift
[SDKS-2199](https://bugster.forgerock.org/jira/browse/SDKS-2199) Authenticator SDK fails to decode some of the PUSH notification JWTs
The SDK fails to decode the payload of some received JWT.
> SDKS-2199 Authenticator SDK fails to decode some notification JWTs

- FRAuth/FRAuth/Callbacks/WebAuthnAuthenticationCallback.swift
- FRAuth/FRAuth/Callbacks/WebAuthnRegistrationCallback.swift
- FRAuth/FRAuth/Constants/Typealias.swift
- FRAuth/FRAuth/Error/WebAuthnError.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/Authenticator.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorGetAssertionSession.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorMakeCredentialSession.swift
- FRAuth/FRAuth/WebAuthn/Client/Client.swift
- FRAuth/FRAuth/WebAuthn/Client/Operation/ClientCreateOperation.swift
- FRAuth/FRAuth/WebAuthn/Client/Operation/ClientGetOperation.swift
- FRAuth/FRAuth/WebAuthn/WAKTypes.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/WebAuthnRegistrationCallbackTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnAuthenticationTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/WebAuthnRegistrationTests.swift
[SDKS-2226](https://bugster.forgerock.org/jira/browse/SDKS-2226)
Made the WAKError and WebAuthError structs to hold more information and surface the platform error and message description
Updated the submitted message to contain the ErrorMessage as the protocol (AM) defines where available
Updated tests
> SDKS-2226_WebAuthn_error_fixes

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Callbacks/WebAuthnRegistrationCallback.swift
- FRAuth/FRAuth/User/FRUser.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/Internal/CredentialSource.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticator.swift
- FRAuth/FRAuth/WebAuthn/FRWebAuthn.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/WebAuthn/FRWebAuthnTests.swift
- SampleApps/FRExample/FRExample/ViewController.swift
Exposing method to clear the credentials for WebAuthn from the WebAuthnRegistration callback and the FRUser class
[SDKS-2279](https://bugster.forgerock.org/jira/browse/SDKS-2279)
> SDKS-2279_Deleting WebAuthn Credentials

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Callbacks/DeviceBindingCallback.swift
- FRAuth/FRAuth/Callbacks/DeviceSigningVerifierCallback.swift
- FRAuth/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticator.swift
- FRAuth/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticatorDelegate.swift
- FRAuth/FRAuth/DeviceBinding/PinCollector.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticatorTests.swift
- FRCore/FRCore/Authenticator/AppPinAuthenticator.swift
- FRCore/FRCore/Authenticator/CryptoKey.swift
- FRCore/FRCoreTests/FRCore/Authenticator/AppPinAuthenticatorTests.swift
[SDKS-2270](https://bugster.forgerock.org/jira/browse/SDKS-2270)
**Custom UI for passcode entry for Application PIN type**
- Added new ApplicationPinDeviceAuthenticatorDelegate for Collecting Pin
- Added new ApplicationPinDeviceAuthenticatorDefaultDelegate for providing default UI for collecting Pin
- Private Key generation and retrieval now accepts optional pin String
- Moved _DeviceBindingCallback.bind_ and _DeviceSigningVerifierCallback.sign_ methods to background thread
- Updated tests
> Add Custom UI for passcode entry for Application PIN type

- FRAuth/FRAuth/DeviceBinding/PinCollector.swift
[SDKS-2237](https://bugster.forgerock.org/jira/browse/SDKS-2237)
Remove the unnecessary code from _DispatchQueue.main.async_ closure
Fix a memory leak caused by a retain cycle
> Fix a memory leak in DefaultPinCollector

- .github/workflows/ci.yaml
- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/DeviceBinding/UserKeySelector.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-06-DeviceSigningVerifierCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/ApplicationPinDeviceAuthenticatorTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/DeviceBinding/DeviceAuthenticatorTests.swift
[SDKS-2024](https://bugster.forgerock.org/jira/browse/SDKS-2024) JWS Verifier QA 
Added e2e test cases for the Device Signing Verifier node/callback. 
Note that this test cases assume that `device-verifier` tree is present on the target AM with the following configuration:
> SDKS-2024 E2E Test Cases for Device Signing Verifier callback

- FRAuthenticator/FRAuthenticator/Model/Mechanism/Mechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/HOTPMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Mechanism/OATH/TOTPMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/AuthenticatorManager/AuthenticatorManagerTests.swift
[SDKS-2389](https://bugster.forgerock.org/jira/browse/SDKS-2389) Push notifications received and processed for locked accounts
As part of the Authenticator Policies enforcement, the SDK should not allow process the push notification authentication request.
> SDKS-2389 Push notifications received and processed for locked accounts

- CHANGELOG.md
- FRFacebookSignIn.podspec
- FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
- FRFacebookSignIn/FRFacebookSignIn/Sources/FacebookSignInHandler.swift
- Package.swift
- SampleApps/FRExample/FRExample/AppDelegate.swift
[SDKS-1839](https://bugster.forgerock.org/jira/browse/SDKS-1839)
[Spike] Upgrade Facebook SDK iOS
Upgrade Facebook SDK version from 9.1.0 to 16.0.1 in the following places:
- Package.swift
- FRFacebookSignIn.podspec
- FRFacebookSignIn.xcodeproj/project.pbxproj
Add new `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool` method in FRFacebookSignIn that calls `ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`. This method needs to be called in AppDelegate's `application(_ , didFinishLaunchingWithOptions)` method as per Facebook SDK's new requirement in order to initialize the Facebook SDK
Update FRExample's AppDelegate
> Sdks 1839 update facebook sdk

- CHANGELOG.md
- FRAuth.podspec
- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuthenticator.podspec
- FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
- FRCore.podspec
- FRCore/FRCore.xcodeproj/project.pbxproj
- FRCore/FRCore/Log/Log.swift
- FRDeviceBinding.podspec
- FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
- FRFacebookSignIn.podspec
- FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
- FRGoogleSignIn.podspec
- FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
- FRProximity.podspec
- FRProximity/FRProximity.xcodeproj/project.pbxproj
- FRUI.podspec
- FRUI/FRUI.xcodeproj/project.pbxproj
- SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
[SDKS-2548](https://bugster.forgerock.org/jira/browse/SDKS-2548) ForgeRock iOS SDK 4.1.0-beta1 Release
Release preparation for the ForgeRock Android SDK 4.1.0-beta1.
This release includes only one bug-fix in the Authenticator module - [SDKS-2542](https://bugster.forgerock.org/jira/browse/SDKS-2542) [FRA] Combined MFA Registration not working properly
> ForgeRock iOS SDK 4.1.0-beta1 release preparation

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
- FRAuthenticator/FRAuthenticator/Model/Mechanism/Push/PushMechanism.swift
- FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/RequestInterceptor/RequestInterceptorTests.swift
- SampleApps/FRAuthenticatorExample/FRAuthenticatorExample/Controller/NotificationRequestViewController.swift
[SDKS-2545](https://bugster.forgerock.org/jira/browse/SDKS-2545)
Add Interceptor support for PUSH_REGISTER and PUSH_AUTHENTICATE Action types 
Add unit tests
> Add Interceptor support for PUSH_REGISTER and PUSH_AUTHENTICATE Action types 

- FRAuth/FRAuth/User/FRUser.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/User/FRUserTests.swift
- SampleApps/FRExample/FRExample/ViewController.swift
- Making "refresh" and "refreshSync" methods Public
- Updating tests
SDKS-2563
> SDKS-2563 - Making "refresh" and "refreshSync" methods Public

- FRAuth/FRAuth/Config/OAuth2Client.swift
- FRAuth/FRAuth/Manager/TokenManager.swift
- FRAuth/FRAuth/User/FRUser.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/User/FRUserTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/RequestInterceptor/FRRequestInterceptorTests.swift
[SDKS-2571](https://bugster.forgerock.org/jira/browse/SDKS-2571)
Revoke old access_token upon force refresh. Made sure it's only revoking the access token and not the refresh token.
**The following regression test has been completed (this test has been verified with "Issue Refresh Tokens on Refreshing Access Tokens" both On and Off in AM console)**
1. Call Login - Verify that access token and refresh token has been issued
2. Call Get User Info - Verify that user info successfully retrieved using the Access Token from Step 1
3. Call Refresh Token - Verify that the new Access Token has been issued (check that it's different from the Access Token from Step 1) and that Revoke endpoint has been called with the old Access Token from Step 1
4. Call Get User Info - Verify that user info …
> Revoke old access_token upon force refresh

- CHANGELOG.md
- FRAuthenticator/FRAuthenticator/Manager/AuthenticatorManager.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/FRAClient/FRAClientTests.swift
[SDKS-2627](https://bugster.forgerock.org/jira/browse/SDKS-2627) Combined MFA should throw DuplicatedMechanismException for existing accounts
While registering a Combined MFA account, the SDK should throw a Duplicated mechanism error if any of the included mechanisms is already registered on the app.
> Combined MFA should throw Duplicated Mechanism error

- FRAuthenticator/FRAuthenticator/Model/Mechanism/Push/PushQRCodeParser.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/AuthenticatorManager/AuthenticatorManagerTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Util/PushQRCodeParserTests.swift
[SDKS-2653](https://bugster.forgerock.org/jira/browse/SDKS-2653) Issuer parameter not correctly set
While registering a Push mechanism through iOS SDK, the issuer value is incorrect. It shows "forgerock", instead of the issuer value set in the 'Push registration node' property.
> SDKS-2653 Issuer parameter not correctly set for some URI schemes

- FRAuth/FRAuth/User/Browser.swift
Setting the `config.entersReaderIfAvailable` to "false" as this can c…ause the centralized login flow to load in a reader view blocking users to authenticate
SDKS-2746
> SafariviewController reader fix

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth.xcodeproj/xcshareddata/xcschemes/FRAuth.xcscheme
- FRAuth/FRAuth/AppIntegrity/FRAppAttestDomainModal.swift
- FRAuth/FRAuth/AppIntegrity/FRAppAttestServiceImpl.swift
- FRAuth/FRAuth/Callbacks/CallbackFactory.swift
- FRAuth/FRAuth/Callbacks/FRAppIntegrityCallback.swift
- FRAuth/FRAuth/Constants/CallbackConstants.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_07_AppIntegrityTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/AppIntegrity/FRAppAttestDomainModalTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/AppIntegrity/FRAppAttestServiceImplTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/FRAppIntegrityCallbackTests.swift
- FRUI/FRUI/ViewControllers/AuthStepViewController.swift
- SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
> AppIntegrity Feature

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Device/TelephonyCollector.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Device/TelephonyCollectorTests.swift
- FRTestHost/FRTestHost/FRAuthConfigPKHash.plist
[SDKS-2776](https://bugster.forgerock.org/jira/browse/SDKS-2776)
Fix the issue in TelephonyCollector for dual sim phones iOS15 and less
> Fix the issue in TelephonyCollector for dual sim phones iOS15 and less

- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-06-DeviceSigningVerifierCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FRURLProtocol/FRURLProtocolTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Policy/AuthorizationPolicyTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/SSL Pinning/SSLPinningTests.swift
- FRCore/FRCoreTests/FRCore/Network/FRSecurityConfigurationTests.swift
- FRCore/FRCoreTests/FRCore/Network/RequestTests.swift
- FRCore/FRCoreTests/FRCore/Network/RestClientTests.swift
- FRCore/FRCoreTests/FRCore/RequestInterceptor/RequestInterceptorTests.swift
- FRTestHost/FRTestHost.xcodeproj/xcshareddata/xcschemes/FRTestHost.xcscheme
- FRTestHost/FRTestHost/FRAuthConfigPKHash.plist
- FRTestHost/FRTestHost/SharedTestFiles/BaseTest/FRBaseTestCase.swift
[SDKS-2637](https://bugster.forgerock.org/jira/browse/SDKS-2637)
[iOS] Review/Fix unstable/flaky tests in iOS
Improve unit tests
Move hard coded URLs to one place
Change test url
> Improve unit tests, move hard coded URLs to one place, change test url

- FRDeviceBinding/FRDeviceBinding/Sources/ApplicationPinDeviceAuthenticator.swift
- FRDeviceBinding/FRDeviceBindingTests/ApplicationPinDeviceAuthenticatorTests.swift
During the release testing we discovered that there has been a bug related custom claims implementation. This PR fixes that bug.
- Fix a bug where ApplicationPinDeviceAuthenticator wasn't overriding  sign method with custom claims. 
- Add unit tests
> Fix custom claims bug, add unit tests

- CHANGELOG.md
- FRDeviceBinding/FRDeviceBinding/Sources/ApplicationPinDeviceAuthenticator.swift
- FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/Binding.swift
- FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/DeviceBindingCallback.swift
- FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/DeviceSigningVerifierCallback.swift
- FRDeviceBinding/FRDeviceBinding/Sources/DeviceBindingAuthenticators.swift
- FRDeviceBinding/FRDeviceBindingTests/DeviceBindingCallbackTests.swift
- FRDeviceBinding/FRDeviceBindingTests/DeviceSigningVerifierCallbackTests.swift
- SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
- SampleApps/FRExample/FRExample/Playground.swift
- SampleApps/FRExample/FRExample/ViewController.swift
[SDKS-2886](https://bugster.forgerock.org/jira/browse/SDKS-2886)
Fix Device Binding API access level
Fix device binding inheritance issues  
1. Make Binding protocol and methods public
2. Make all **DeviceAuthenticator** subclasses init methods public
3. Add Playground.swift in the example app for validating API Access level during compilation
4. Fix typos in ViewController file.
5.  Update CHANGELOG
6. Refactor Device Binding to fix the inheritance issue caused by Swift protocol's default implementation limitations
------------
Apart from the bug that we had, where our Authenticators had internal init methods, we also found another issue while testing this fix. 
Turns out Swift protocol's default implementation has an UNEXPECTED limitation during inheritance. 
Protocol **A** defines …
> Sdks 2886 Fix Device Binding API access level

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Callbacks/CallbackFactory.swift
- FRAuth/FRAuth/Callbacks/TextInputCallback.swift
- FRAuth/FRAuth/Constants/CallbackConstants.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_08_TextInputCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/CallbackConstantsTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Callback/TextInputCallbackTests.swift
- FRUI/FRUI/Model/CallbackTableViewCellFactory.swift
- FRUI/FRUI/Views/NameCallbackTableViewCell.swift
- SampleApps/FRExample/FRExample/ViewController.swift
- SampleApps/FRexampleObjC/FRexampleObjC/ViewController.m
[SDKS-546](https://bugster.forgerock.org/jira/browse/SDKS-546) TextInputCallback Support
Adding support in the SDK to handle the TextInputCallback and provide a corresponding samples.
> SDKS-546 TextInputCallback Support

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_09_PingOneProtectInitializeCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_10_PingOneProtectEvaluateCallbackTest.swift
- PingProtect/PingProtect/Sources/Callbacks/PingOneProtectEvaluationCallback.swift
- PingProtect/PingProtectTests/PingOneProtectEvaluationCallbackTests.swift
- SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
[SDKS-2898](https://bugster.forgerock.org/jira/browse/SDKS-2898) "Test Protect SDK"
- Added e2e tests for the PingOne Protect support
These test cases require the following authentication trees present in AM:
**TEST_PING_ONE_PROTECT_INITIALIZE**:
**TEST_PING_ONE_PROTECT_EVALUATE**:
> SDKS-2898 e2e test cases for the PingOne Protect module

- Package.swift
- PingProtect.podspec
- PingProtect/PingProtect.xcodeproj/project.pbxproj
- PingProtect/PingProtect/Sources/Callbacks/PingOneProtectInitializeCallback.swift
[SDKS-3078](https://bugster.forgerock.org/jira/browse/SDKS-3078)  [iOS] Protect module bug fixes
1. Add missing `import Foundation` in PingOneProtectInitializeCallback.swift
2. Fix Incorrect link for 'PingOneSignals' podspec (should be :podspec => "https://assets.pingone.com/signals/ios-sdk/5.2.1/)
3. Update Signals SDK to 5.2.1
> Protect bug fixes

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuth/Device/HardwareCollector.swift
- FRAuth/FRAuth/PrivacyInfo.xcprivacy
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Device/FRDeviceCollectorTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Network/NetworkReachabilityMonitorTests.swift
- FRCore/FRCore.xcodeproj/project.pbxproj
- FRCore/FRCore/PrivacyInfo.xcprivacy
- FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
- FRDeviceBinding/FRDeviceBinding/PrivacyInfo.xcprivacy
- FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
- FRFacebookSignIn/FRFacebookSignIn/PrivacyInfo.xcprivacy
- FRGoogleSignIn.podspec
- FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
- FRGoogleSignIn/FRGoogleSignIn/PrivacyInfo.xcprivacy
- FRProximity/FRProximity.xcodeproj/project.pbxproj
- FRProximity/FRProximity/PrivacyInfo.xcprivacy
- FRUI/FRUI.xcodeproj/project.pbxproj
- FRUI/FRUI/PrivacyInfo.xcprivacy
- Package.resolved
- Package.swift
- PingProtect.podspec
- PingProtect/PingProtect.xcodeproj/project.pbxproj
- PingProtect/PingProtect/PrivacyInfo.xcprivacy
[SDKS-3086](https://bugster.forgerock.org/jira/browse/SDKS-3086)
[iOS] Add Privacy Manifests to SDK
1. Update Google SDK to 7.1.0
2. Remove storage(diskSpace) from HardwareCollector
3. Add Privacy Manifests to all modules
4. Update Signals SDK to 5.2.3
5. Update FRFacebookSignIn Privacy Manifest to reflect Facebook iOS SDK privacy manifest
6. Change SPM dependency versions from exactVersion to upToNextMinorVersion
> Sdks 3086 privacy manifests

- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorMakeCredentialSession.swift
- FRAuth/FRAuth/WebAuthn/Client/Operation/ClientCreateOperation.swift
- FRAuth/FRAuth/WebAuthn/FRWebAuthn.swift
[SDKS-3244](https://bugster.forgerock.org/jira/browse/SDKS-3244) Fix "usernameless" WebAuthn Tests
This reverts a previous change where the PublicKeyCredentialSource where stored for all WebAuthn use cases.
> SDKS-3244 Only store PublicKeyCredentialSource when requireResidentKey is true

- FRAuth/FRAuth/Config/FROptions.swift
- FRAuth/FRAuth/Config/OAuth2Client.swift
- FRAuth/FRAuth/Constants/OAuth2.swift
- FRAuth/FRAuth/FRAuth.swift
- FRAuth/FRAuth/User/Browser.swift
- FRAuth/FRAuth/User/FRUser.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Browser/BrowserTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FRAuth/FRAuthTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FROptions/FROptionsTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/User/FRUserBrowserTests.swift
- FRTestHost/FRTestHost/SharedTestFiles/TestConfig/Config.json
- FRTestHost/FRTestHost/SharedTestFiles/TestConfig/Config.swift
- SampleApps/FRExample/FRExample/ViewController.swift
[SDKS-3021](https://bugster.forgerock.org/jira/browse/SDKS-3021)
[iOS] Centralize Oidc Signoff with PingOne
1. A new logout method has been added to FRUser. It takes presentingViewController and browserType arguments
2. If oauthSignoutRedirectUri is provided in the config/options, the sdk will perform browser logout
3. Works with all browser types. Same browser type need to be used for browser login and logout
4. Might add more Browser login/logout tests
> Sdks 3021 OIDC signoff

- FRAuth/FRAuth/User/FRUser.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/User/FRUserBrowserTests.swift
[SDKS-3301](https://bugster.forgerock.org/jira/browse/SDKS-3301)
[iOS] FRUser.logout(...) should not invoke endSession when oauthSignoutRedirectUri is present in the configuration
> Fix the issue when session would get revoked twice during browser logout

- CHANGELOG.md
- FRAuth.podspec
- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_07_AppIntegrityTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Browser/BrowserTests.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/Model/User/FRUserBrowserTests.swift
- FRAuthenticator.podspec
- FRAuthenticator/FRAuthenticator.xcodeproj/project.pbxproj
- FRCore.podspec
- FRCore/FRCore.xcodeproj/project.pbxproj
- FRCore/FRCore/Log/Log.swift
- FRDeviceBinding.podspec
- FRDeviceBinding/FRDeviceBinding.xcodeproj/project.pbxproj
- FRFacebookSignIn.podspec
- FRFacebookSignIn/FRFacebookSignIn.xcodeproj/project.pbxproj
- FRGoogleSignIn.podspec
- FRGoogleSignIn/FRGoogleSignIn.xcodeproj/project.pbxproj
- FRProximity.podspec
- FRProximity/FRProximity.xcodeproj/project.pbxproj
- FRUI.podspec
- FRUI/FRUI.xcodeproj/project.pbxproj
- PingProtect.podspec
- PingProtect/PingProtect.xcodeproj/project.pbxproj
- SampleApps/FRExample/FRExample.xcodeproj/project.pbxproj
[SDKS-3206](https://bugster.forgerock.org/jira/browse/SDKS-3206) Release activities for ForgeRock iOS SDK 4.5.0
- Updated CHANGELOG.md
- Disabled all "App Integrity" tests
- Disabled some failing on BitBar "Browser Login" tests (see [SDKS-3304](https://bugster.forgerock.org/jira/browse/SDKS-3304))
> SDKS-3206 ForgeRock iOS SDK 4.5.0 Release

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA_12_ReCaptchaEnterpriseCallbackTest.swift
- FRCaptchaEnterprise/FRCaptchaEnterprise.xcodeproj/project.pbxproj
- FRCaptchaEnterprise/FRCaptchaEnterprise/Sources/Callbacks/ReCaptchaEnterpriseCallback.swift
- FRCaptchaEnterprise/FRCaptchaEnterpriseTests/ReCaptchaEnterpriseTests.swift
- FRTestHost/FRTestHost/FRAuthConfigPKHash.plist
- Package.swift
- SampleApps/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
[SDKS-3373](https://bugster.forgerock.org/jira/browse/SDKS-3373) [QA] Test end-to-end flow of ReCaptcha Enterprise
- Added e2e test cases for the ReCaptcha Enterprise feature. These test cases test both server and client side. These require _live_ server and the following authentication tree:
> SDKS-3373 - ReCaptcha e2e test cases

- FRCaptchaEnterprise.podspec
- FRUI.podspec
- Update RecaptchaEnterprise from 18.1.0 to 18.6.0
- Add s.static_framework = true in FRCaptchaEnterprise.podspec and FRUI.podspec
- Remove  base_dir + '/Assets/*' from resources in FRUI.podspec
> Update FRCaptchaEnterprise and FRUI podspecs

- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-05-DeviceBindingCallbackTest.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/E2ETests/Callback-Live/AA-06-DeviceSigningVerifierCallbackTest.swift
- FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/DeviceBindingCallback.swift
- FRDeviceBinding/FRDeviceBinding/Sources/Callbacks/DeviceSigningVerifierCallback.swift
- FRDeviceBinding/FRDeviceBindingTests/DeviceBindingCallbackTests.swift
- FRDeviceBinding/FRDeviceBindingTests/DeviceSigningVerifierCallbackTests.swift
Allowing DeviceBinding `NONE` option on Simulators
> Allowing DeviceBinding `NONE` option on Simulators

- CHANGELOG.md
- FRAuth/FRAuth/Config/FROptions.swift
- FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FROptions/FROptionsTests.swift
- FRTestHost/FRTestHost/SharedTestFiles/TestData/MockResponseData/Discovery/discoveryWithPingEndIdp.json
[SDKS-3424](https://pingidentity.atlassian.net/browse/SDKS-3424)
[iOS] Handle New Signout with ID Token for PingOne Platform
> Add support for Sign out with ID Token for PingOne Platform

- FRAuthenticator/FRAuthenticator/FRAClient.swift
- FRAuthenticator/FRAuthenticator/Manager/AuthenticatorManager.swift
- FRAuthenticator/FRAuthenticator/Push/FRAPushHandler.swift
- FRAuthenticator/FRAuthenticator/Storage/KeychainServiceClient.swift
- FRAuthenticator/FRAuthenticator/Storage/StorageClient.swift
- FRAuthenticator/FRAuthenticatorTests/E2ETests/FRAClient/FRAClientTests.swift
- FRAuthenticator/FRAuthenticatorTests/TestUtils/DummyStorageClient.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Push/FRAPushHandlerTests.swift
- FRAuthenticator/FRAuthenticatorTests/UnitTests/Storage/KeychainServiceStorageClientTests.swift
[SDKS-3533](https://pingidentity.atlassian.net/browse/SDKS-3533) [iOS][Authenticator] Prevent duplicated notification on iOS SDK
The iOS SDK does not verify whether a push notification with an identical identifier has already been stored, delegating this responsibility to the application developer. This PR include the following changes:
- Added a new `getNotificationByMessageId` method to the `StorageClient` and `FRAClient` 
- Updated the `FRAPushHandler` class to check whether a payload was already persisted
- Update unit tests
> SDKS-3533 Prevent duplicated notification on iOS SDK

- FRDeviceBinding/FRDeviceBinding/Sources/DeviceBindingAuthenticators.swift
Changing the default BiometricAndFallback authenticator to respect "biometryCurrentSet, .or, .devicePasscode" in order to fail the biometric if the current set has changed
Please, link [jira ticket ](https://pingidentity.atlassian.net/browse/SDKS-3963) here.
> SDKS-3963_DeviceBinding_biometry_change

- FRAuth/FRAuth.xcodeproj/project.pbxproj
- FRCaptchaEnterprise.podspec
- FRCaptchaEnterprise/FRCaptchaEnterprise.xcodeproj/project.pbxproj
- FRCaptchaEnterprise/FRCaptchaEnterpriseTests/ReCaptchaEnterpriseTests.swift
- Package.swift
- e2e/FRExample.xcworkspace/xcshareddata/swiftpm/Package.resolved
[SDKS-3927](https://pingidentity.atlassian.net/browse/SDKS-3927) [RFE][iOS]: Out of date with reCAPTCHA 18.7.0
Updated Recaptcha version to 18.7.0 from 18.6.0
Even though this didn't break anything in the **FRCaptchaEnterprise** library, it broke our tests and made them more restricted.
Notably in this version (18.7.0) they made two changes that affected our tests.
1. They removed the ability to initialize `RecaptchaError` with domain, error code and message ( `RecaptchaError(domain: "com.google.recaptcha", code: .errorCodeInternalError, message: "INVALID_CAPTCHA_CLIENT")` code no longer works )
2. They removed public access to action property from RecaptchaAction class ( `capturedAction.action` no longer works)
> Update Recaptcha library to 18.7.0, fix tests

- FRAuth/FRAuth/WebAuthn/Authenticator/Internal/CredentialStore.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/Internal/KeySupport.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorGetAssertionSession.swift
- FRAuth/FRAuth/WebAuthn/Authenticator/PlatformAuthenticator/PlatformAuthenticatorMakeCredentialSession.swift
- FRAuth/FRAuth/WebAuthn/Client/Client.swift
- FRAuth/FRAuth/WebAuthn/FRWebAuthnManager.swift
- FRCore/FRCore/Util/FRDataUtil.swift
- FRCore/FRCore/Util/FRStringUtil.swift
[SDKS-4299](https://pingidentity.atlassian.net/browse/SDKS-4299) [SPIKE] [iOS] Validate Legacy and Unified SDKs for Xcode 26
Rename Data extension bytes property to bytesArray to avoid Xcode26 issues
> Rename Data extension bytes property to bytesArray to avoid Xcode26 issues
